name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-preview:
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.page_url }}pr-${{ github.event.pull_request.number }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build site
        run: make html

      - name: Prepare site for deployment
        run: |
          # Create PR-specific directory
          mkdir -p _site/pr-${{ github.event.pull_request.number }}
          # Copy the built files to the PR-specific directory
          cp -r build/html/* _site/pr-${{ github.event.pull_request.number }}/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const baseUrl = `${{ steps.deployment.outputs.page_url }}`;
            const prNumber = context.issue.number;
            const previewUrl = `${baseUrl}pr-${prNumber}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `✨ Preview deployment for PR #${prNumber} is ready!\nPreview URL: ${previewUrl}\n\nThis preview will update automatically when new changes are pushed.`
            });